blank_issues_enabled: false
contact_links:
    - name: ğŸ™ Ask a Question
      url: https://github.com/allysonsilva/laravel-multienv/discussions/new?category=q-a
      about: Ask the community for help
